// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressImage(arg1:string,arg2:number):Promise<string>;

export function Greet(arg1:string):Promise<string>;
