// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CompressImage(arg1:string,arg2:number,arg3:string):Promise<main.Result>;

export function Greet(arg1:string):Promise<string>;

export function SelectFile():Promise<string>;

export function SelectOutputFolder():Promise<string>;
