// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CompressImage(arg1:string,arg2:number,arg3:string):Promise<main.Result>;

export function Greet(arg1:string):Promise<string>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectMultipleFiles():Promise<Array<string>>;

export function SelectOutputFolder():Promise<string>;
